title: "Weikang Hu"
description: "PhD student in Economics · The Chinese University of Hong Kong, Shenzhen"
theme: jekyll-theme-minimal
show_downloads: false
lang: en
url: "https://weikanghu1.github.io"
